In [30]:
import pandas as pd

In [31]:
n = 4
df = pd.read_csv("C:/Users/zmoha/OneDrive/Bureau/Data VIZ/LAB2/st_app/projet/full_2020.csv", sep=',', error_bad_lines=False,header=0, skiprows=lambda i: i % n != 0, low_memory=False)
df1 = pd.read_csv("C:/Users/zmoha/OneDrive/Bureau/Data VIZ/LAB2/st_app/projet/full_2019.csv", sep=',', error_bad_lines=False,header=0, skiprows=lambda i: i % n != 0, low_memory=False)
df2 = pd.read_csv("C:/Users/zmoha/OneDrive/Bureau/Data VIZ/LAB2/st_app/projet/full_2018.csv", sep=',', error_bad_lines=False,header=0, skiprows=lambda i: i % n != 0, low_memory=False)
df3 = pd.read_csv("C:/Users/zmoha/OneDrive/Bureau/Data VIZ/LAB2/st_app/projet/full_2017.csv", sep=',', error_bad_lines=False,header=0, skiprows=lambda i: i % n != 0, low_memory=False)
df4 = pd.read_csv("C:/Users/zmoha/OneDrive/Bureau/Data VIZ/LAB2/st_app/projet/full_2016.csv", sep=',', error_bad_lines=False,header=0, skiprows=lambda i: i % n != 0, low_memory=False)

C:\Users\zmoha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\IPython\core\interactiveshell.py:3441: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [32]:
a = df.drop(df.columns[[0, 2,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,36]], axis=1)
b = df1.drop(df.columns[[0, 2,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,36]], axis=1)
c = df2.drop(df.columns[[0, 2,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,36]], axis=1)
d = df3.drop(df.columns[[0, 2,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,36]], axis=1)
e = df4.drop(df.columns[[0, 2,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,36]], axis=1)

In [33]:
a

,date_mutation,nature_mutation,valeur_fonciere,code_departement,type_local,surface_reelle_bati,nombre_pieces_principales,nature_culture,surface_terrain,longitude,latitude
0,2020-01-02,Vente,2175.0,01,NaN,NaN,NaN,terres,1940.0,4.882347,46.246519
1,2020-01-07,Vente,123.0,01,NaN,NaN,NaN,sols,55.0,5.344396,46.263943
2,2020-01-09,Vente,72000.0,01,Maison,35.0,2.0,sols,381.0,5.350973,46.380911
3,2020-01-03,Vente,350750.0,01,NaN,NaN,NaN,sols,19.0,5.200885,46.209963
4,2020-01-03,Vente,350750.0,01,Dépendance,NaN,0.0,jardins,1267.0,5.200634,46.210371
...,...,...,...,...,...,...,...,...,...,...,...
614885,2020-12-16,Vente,1937500.0,75,Appartement,37.0,2.0,sols,447.0,2.350481,48.854293
614886,2020-12-16,Vente,1937500.0,75,Appartement,110.0,5.0,sols,447.0,2.350481,48.854293
614887,2020-12-16,Vente,1937500.0,75,Appartement,46.0,2.0,sols,447.0,2.350481,48.854293
614888,2020-12-16,Vente,1937500.0,75,Appartement,87.0,4.0,sols,447.0,2.350481,48.854293
614889,2020-10-08,Adjudication,255000.0,75,Appartement,21.0,1.0,NaN,NaN,2.348149,48.865935

In [34]:
q = a.dropna().drop_duplicates()
s = b.dropna().drop_duplicates()
f = c.dropna().drop_duplicates()
g = d.dropna().drop_duplicates()
h = e.dropna().drop_duplicates()

In [35]:
q.to_csv('2020.csv')
s.to_csv('2019.csv')
f.to_csv('2018.csv')
g.to_csv('2017.csv')
h.to_csv('2016.csv')